### ISSUE TITLE
useState within App directory isn't working (anymore?)

### ISSUE THREAD

**Issue by NoobFullStack** [benjaminhaig/next-13-tutorial#1]
You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

```
   ,-[E:\Development\Web\repo-testing\next-13-tutorial\app\blog\[slug]\page.tsx:1:1]
 1 | import React, { useState } from "react";
   :                 ^^^^^^^^
```

Running same nextjs version as your package.json file:
```
PS E:\Development\Web\repo-testing\next-13-tutorial> npx next -v           
Next.js v13.4.5
```

What should be done? I am having a hard time implementing generateStaticParams properly. Most tutorials only show the creation of routes; that's good.. But need to have content as well; which your repo provided.. 

Any idea what to do? Or should I just mark is as "use client" anyway?

**Comment by benjaminhaig** [comment]
Hi thanks for reaching out,

Can you share me on your repo and I'll take a look for you? Hard to tell without the file in front of me.

Cheers

**Comment by NoobFullStack** [comment]
Hi there. The error was received directly after cloning your repo -> [branch lesson-4](https://github.com/benjaminhaig/next-13-tutorial/tree/lesson-4)

Though, I removed the useState, had to adjust the code anyway since I use sqlite3, no Firebase. Had a hard time wrapping my head around using generateStaticParams and than also display the content :)) 

Huge thanks for the example provided!! For me issue resolved <3
